### ISSUE TITLE
Default timeout should be None

### ISSUE THREAD

**Issue by mocsar** [pywebhdfs/pywebhdfs#31]
The following error occures after upgarding to 0.4.0:

```
Traceback (most recent call last):
  ...
  File "/usr/lib/python2.7/site-packages/pywebhdfs/webhdfs.py", line 344, in get_file_dir_status
    path, operations.GETFILESTATUS)
  File "/usr/lib/python2.7/site-packages/pywebhdfs/webhdfs.py", line 689, in _resolve_host
    timeout=self.timeout)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(119, 'Operation now in progress'))
```

The default timeout of requests is None so it would be better to use None instead of 0:

```python
class PyWebHdfsClient(object):
    pass

    def __init__(self, host='localhost', port='50070', user_name=None,
                 path_to_hosts=None, timeout=None):
        pass
```

**Comment by tiangolo** [comment]
Agree, the same happened to me. Thanks for reporting it.

**Comment by mike-heckman** [comment]
By the way, based on this issue: https://github.com/kennethreitz/requests/issues/2699

Setting the timeout to None has other consequences and may not work for much longer.

**Comment by mocsar** [comment]
Thank you!
