### ISSUE TITLE
Accessing WebHdfs through Knox Gateway 

### ISSUE THREAD

**Issue by prabhu1984** [pywebhdfs/pywebhdfs#44]
Hi,

Can you give me some example how to use pywebhdfs to access through Knox gateway?

I'm getting "SSL3_GET_SERVER_CERTIFICATE:certificate verify failed" error, when I tried like below.
///
$ PYTHONPATH=~/pywebhdfs:~/six:~/requests python
Python 2.6.6 (r266:84292, May 22 2015, 08:34:51) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pywebhdfs.webhdfs import PyWebHdfsClient
>>> hdfs = PyWebHdfsClient(base_uri_pattern='https://localhost:8443/gateway/default/webhdfs/v1',request_extra_opts={'verify': '/etc/ssl/certs/ca-bundle.crt','auth': ('prabhu', 'password')})
>>> my_data = '01010101010101010101010101010101'
>>> my_file = 'user/livy/myfile.txt'
>>> hdfs.append_file(my_file, my_data)
~/requests/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
~/requests/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/pywebhdfs/pywebhdfs/webhdfs.py", line 160, in append_file
    **optional_args)
  File "~/pywebhdfs/pywebhdfs/webhdfs.py", line 703, in _resolve_host
    **self.request_extra_opts)
  File "~/requests/requests/api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "~/requests/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "~/requests/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "~/requests/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "~/requests/requests/adapters.py", line 477, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:492: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
>>> quit()
///

But, I'm successfully able to list webhdfs through below commands (on both Knox and Direct webhdfs).

curl --silent -k -u prabhu:password 'https://localhost:8443/gateway/default/webhdfs/v1/user/?op=LISTSTATUS'

curl --silent --negotiate -u:prabhu: 'http://namenode1:50070/webhdfs/v1/user/?op=LISTSTATUS'

Please let me know, how to fix this issue.

Thanks
Prabhu!

**Comment by snowch** [comment]
Hi Prabhu,  it sounds like you may need to use a newer python version.  Alternatively, because you are using the `-k` (insecure) option to curl, assuming that security is not a top priority, you could do the same with `'verify': False`: 

```
hdfs = PyWebHdfsClient(
   base_uri_pattern="https://yourhostname:8443/gateway/default/webhdfs/v1",
   request_extra_opts={'verify': False, 'auth': ('yourusername', 'your password')}
)
```
