### ISSUE TITLE
requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:579)

### ISSUE THREAD

**Issue by ankitpateledu** [pywebhdfs/pywebhdfs#53]
I am trying to access hdfs from a remote node which is not part of hdfs cluster. i tried hdfsCLI and pywebhdfs apis but i run into same issue in both cases.

**requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:579)**

i have 5 nodes, node A is hadoop master; B,C,D are datanodes. node z is not part of hadoop cluster, from here i want to access (read, write, make dirs, rm dirs etc) hdfs.
i have CentOS 7 with python 2.7.5 on all nodes.

following is the python code and error using pywebhdfs, i am running on node Z.
`from pywebhdfs.webhdfs import PyWebHdfsClient`
`hdfs = PyWebHdfsClient(host='hostname or ip',port='50070', user_name='root')`
`hdfs.list_dir('/')`

`Traceback (most recent call last):`
`File "<stdin>", line 1, in <module>`
`File "/usr/lib/python2.7/site-packages/pywebhdfs/webhdfs.py", line 480, in list_dir`
`path, operations.LISTSTATUS)`
`File "/usr/lib/python2.7/site-packages/pywebhdfs/webhdfs.py", line 703, in _resolve_host`
`**self.request_extra_opts)`
`File "/usr/lib/python2.7/site-packages/requests/api.py", line 70, in get`
`return request('get', url, params=params, **kwargs)`
`File "/usr/lib/python2.7/site-packages/requests/api.py", line 56, in request`
`return session.request(method=method, url=url, **kwargs)`
`File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 488, in request`
`resp = self.send(prep, **send_kwargs)`
`File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 609, in send`
`r = adapter.send(request, **kwargs)`
`File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 497, in send`
`raise SSLError(e, request=request)`
`requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:579)`

i get a sense that it is some network related issue. all nodes A to Z are listed in /etc/hosts file and they have password less SSH access to each other.

i also tried same code on node A; hadoop master node. here if i use hostname or ip i get exactly same error; but if i use "localhost" it works fine.

also webhdfs access using curl command works fine from node Z
https://bighadoop.wordpress.com/2013/06/02/hadoop-rest-api-webhdfs/

can you help me understand whats the issue here and what am i missing on my nodes so i can use hdfs apis for python like hdfsCLI and pywebHDFS

thanks

**Comment by swimmingbean** [comment]
Do you have SSL enabled on the name node/data nodes?

<property>
<name>dfs.http.policy</name>
<value>HTTPS_ONLY</value>
</property>

**Comment by TonyG-Dev** [comment]
Any news on this topic ?

**Comment by ankitpateledu** [comment]
its been a while i do recall though that the issues was unresolved at a point i was working on it; after some time it lost focus and attention
